### ISSUE TITLE
Exception:  java.util.NoSuchElementException: None.get (data formatted correctly)

### ISSUE THREAD

**Issue by phlatphish** [AbeelLab/ptolemy#11]
I just encountered this. My GFF files only contain the feature type "gene." I wrote out the GFF files myself but they are correctly formatted according to gff3validator. I am able to run the test data without any problem.

I can send you fasta and gff files if that would help.

(Wed Oct 14 17:24:48 MDT 2020): Found 7 genome entries
(Wed Oct 14 17:24:48 MDT 2020): --Verifying paths
(Wed Oct 14 17:24:48 MDT 2020): Constructing database:
(Wed Oct 14 17:24:48 MDT 2020): --Frankia_alni_ACN14a
Exception in thread "main" java.util.NoSuchElementException: None.get
at scala.None$.get(Option.scala:349)
at scala.None$.get(Option.scala:347)
at utilities.GFFutils.getGeneID(GFFutils.scala:60)
at utilities.GFFutils.$anonfun$toGFFLine$1(GFFutils.scala:35)
at build_db.Extract$.$anonfun$extract$4(Extract.scala:95)
at scala.collection.immutable.List.map(List.scala:283)
at build_db.Extract$.constructDataBase$1(Extract.scala:95)
at build_db.Extract$.$anonfun$extract$38(Extract.scala:302)
at build_db.Extract$.$anonfun$extract$38$adapted(Extract.scala:300)
at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
at scala.collection.immutable.List.foldLeft(List.scala:86)
at build_db.Extract$.extract(Extract.scala:300)
at build_db.Extract$.$anonfun$main$1(Extract.scala:59)
at build_db.Extract$.$anonfun$main$1$adapted(Extract.scala:55)
at scala.Option.map(Option.scala:146)
at build_db.Extract$.main(Extract.scala:55)
at cli.Ptolemy$.main(Ptolemy.scala:29)
at cli.Ptolemy.main(Ptolemy.scala)

**Comment by aysunrhn** [comment]
Hi,

May I ask which version of ptolemy you are using? Looking at the error and the code line, it should be version 1.0 but just want to make sure.

I have also looked at your files you had emailed:
`chr1	ppanggolin	gene	85	312	.	+	.	ori=F;family=Frankia_torreyi_CDS_0001;nb_copy_in_org=2;partition=cloud;persistent_neighbors=0;shell_neighbors=0;cloud_neighbors=9`

I think the problem is that features in your annotation files are missing the specific values in the last field that ptolemy looks for when it's parsing GFF files. ptolemy keeps track of these features based on the "locus_tag" or the "Name", neither of these are included in your file. Try adding either of these values in the last field, it should work.

**Comment by phlatphish** [comment]
Thanks,

I couldn't get it to print a version but I am pretty sure it is 1.0 based on the download page.

After some experimenting I found that the ID= and Name= elements in column 9 of the GFF file are necessary and sufficient to make it run successfully.

I have run the three steps: extract, syntenic-anchors and canonical-quiver, and got a GFA file as output.

I was able to open the resulting GFA file in bandage, but not in GfaViz. Have you been able to open ptolemy output in GfaViz?

**Comment by aysunrhn** [comment]
> I have run the three steps: extract, syntenic-anchors and canonical-quiver, and got a GFA file as output.

Let me know if it all works out fine!

> I was able to open the resulting GFA file in bandage, but not in GfaViz. Have you been able to open ptolemy output in GfaViz?

I remember trying GfaViz last year once, but there were minor differences in the gfa output of ptolemy that - if I remember correctly - didn't conform to the standard gfa format. What sort of problem are you having with GfaViz? I may check the gfa specs again
