### ISSUE TITLE
How exactly does the GFF file need to be structured?

### ISSUE THREAD

**Issue by bastian-wur** [AbeelLab/ptolemy#2]
Hi everyone,

I have some issues running ptolemy.
I can run the test data fine, that itself works.
But if I try to run a testset from my own data, I get the following:

```
(Mon Dec 03 17:54:49 CET 2018): Found 11 genome entries
(Mon Dec 03 17:54:49 CET 2018): --Verifying paths
(Mon Dec 03 17:54:49 CET 2018): Constructing database: 
(Mon Dec 03 17:54:49 CET 2018): --g4_4_64
Exception in thread "main" java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:349)
        at scala.None$.get(Option.scala:347)
        at utilities.GFFutils.getGeneName(GFFutils.scala:51)
        at utilities.GFFutils.$anonfun$toGFFLine$1(GFFutils.scala:35)
        at build_db.Extract$.$anonfun$extract$4(Extract.scala:95)
        at scala.collection.immutable.List.map(List.scala:283)
        at build_db.Extract$.constructDataBase$1(Extract.scala:95)
        at build_db.Extract$.$anonfun$extract$38(Extract.scala:302)
        at build_db.Extract$.$anonfun$extract$38$adapted(Extract.scala:300)
        at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
        at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
        at scala.collection.immutable.List.foldLeft(List.scala:86)
        at build_db.Extract$.extract(Extract.scala:300)
        at build_db.Extract$.$anonfun$main$1(Extract.scala:59)
        at build_db.Extract$.$anonfun$main$1$adapted(Extract.scala:55)
        at scala.Option.map(Option.scala:146)
        at build_db.Extract$.main(Extract.scala:55)
        at cli.Ptolemy$.main(Ptolemy.scala:29)
        at cli.Ptolemy.main(Ptolemy.scala)
```

This seems to be an issue with my used GFF files, right?
From the error, I checked further, my GFF files (produced by prokka) do not have any entries for "gene", only "CDS", and none have a "name" field.

Is that by any chance the issue?

Best regards,
Bastian

**Comment by macman123** [comment]
I encountered the same problem when running ptolemy on prokka gff files

**Comment by thomasabeel** [comment]
Experimental release b-0.1 has an option for the extract command that allows you to chose to use "CDS". By default Ptolemy uses "gene".

**Comment by phlatphish** [comment]
I just encountered a similar issue, and my GFF files only contain the feature type "gene."  

(Wed Oct 14 17:24:48 MDT 2020): Found 7 genome entries
(Wed Oct 14 17:24:48 MDT 2020): --Verifying paths
(Wed Oct 14 17:24:48 MDT 2020): Constructing database: 
(Wed Oct 14 17:24:48 MDT 2020): --Frankia_alni_ACN14a
Exception in thread "main" java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:349)
        at scala.None$.get(Option.scala:347)
        at utilities.GFFutils.getGeneID(GFFutils.scala:60)
        at utilities.GFFutils.$anonfun$toGFFLine$1(GFFutils.scala:35)
        at build_db.Extract$.$anonfun$extract$4(Extract.scala:95)
        at scala.collection.immutable.List.map(List.scala:283)
        at build_db.Extract$.constructDataBase$1(Extract.scala:95)
        at build_db.Extract$.$anonfun$extract$38(Extract.scala:302)
        at build_db.Extract$.$anonfun$extract$38$adapted(Extract.scala:300)
        at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
        at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
        at scala.collection.immutable.List.foldLeft(List.scala:86)
        at build_db.Extract$.extract(Extract.scala:300)
        at build_db.Extract$.$anonfun$main$1(Extract.scala:59)
        at build_db.Extract$.$anonfun$main$1$adapted(Extract.scala:55)
        at scala.Option.map(Option.scala:146)
        at build_db.Extract$.main(Extract.scala:55)
        at cli.Ptolemy$.main(Ptolemy.scala:29)
        at cli.Ptolemy.main(Ptolemy.scala)

The GFF files validate OK  with genome tools gff3validator.  

I am able to run the test data without any problem.
