### ISSUE TITLE
invalid directory

### ISSUE THREAD

**Issue by Sanrrone** [AbeelLab/ptolemy#3]
Hi, using the first step I got the error `invalid directory` for the DB destination, I cannot set either with the examples files.
Additionally I tested the beta version and is the same error.

`java -jar ~/Programas/ptolemy-1.0/ptolemy.jar extract -g ptolomyInput.tsv -o ptolemy_db`
```Exception in thread "main" java.lang.AssertionError: assertion failed: The following directory does not exist or it is invalid: /home/sandro/Escritorio/acidithiobacillus/ptolemy_db
	at scala.Predef$.assert(Predef.scala:219)
	at utilities.FileHandling$.verifyDirectory(FileHandling.scala:47)
	at build_db.Extract$.$anonfun$main$1(Extract.scala:57)
	at build_db.Extract$.$anonfun$main$1$adapted(Extract.scala:55)
	at scala.Option.map(Option.scala:146)
	at build_db.Extract$.main(Extract.scala:55)
	at cli.Ptolemy$.main(Ptolemy.scala:29)
	at cli.Ptolemy.main(Ptolemy.scala)```

what can I do?
thank you in advance

**Comment by Sanrrone** [comment]
Ok forget it, the directory must be created by the user.
