### ISSUE TITLE
Index out error and example runs doesn't work

### ISSUE THREAD

**Issue by Sanrrone** [AbeelLab/ptolemy#4]
Hi, I got the Array index out of bounds exception but I don't know why, 
`java -jar ~/Programas/ptolemy-1.0/ptolemy.jar extract -g ptolemyInput.tsv -o ptolemydb`
```(Thu Apr 04 12:08:30 CLST 2019): Found 3 genome entries
(Thu Apr 04 12:08:30 CLST 2019): --Verifying paths
(Thu Apr 04 12:08:30 CLST 2019): Constructing database: 
(Thu Apr 04 12:08:30 CLST 2019): --PQ33
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at utilities.ORFalignments.$anonfun$computeGamma$1(ORFalignments.scala:34)
	at utilities.ORFalignments.$anonfun$computeGamma$1$adapted(ORFalignments.scala:32)
	at utilities.MinimapUtils.$anonfun$collectBestAlignments$1(MinimapUtils.scala:49)
	at utilities.MinimapUtils.$anonfun$collectBestAlignments$1$adapted(MinimapUtils.scala:49)
	at utilities.MinimapUtils.$anonfun$collectBestAlignments$4(MinimapUtils.scala:70)
	at scala.collection.IndexedSeqOptimized.foldLeft(IndexedSeqOptimized.scala:56)
	at scala.collection.IndexedSeqOptimized.foldLeft$(IndexedSeqOptimized.scala:64)
	at scala.collection.mutable.ArrayOps$ofRef.foldLeft(ArrayOps.scala:191)
	at utilities.MinimapUtils.collectBestAlignments(MinimapUtils.scala:66)
	at utilities.MinimapUtils.collectBestAlignments$(MinimapUtils.scala:28)
	at build_db.Extract$.collectBestAlignments(Extract.scala:20)
	at build_db.Extract$.constructDataBase$1(Extract.scala:217)
	at build_db.Extract$.$anonfun$extract$38(Extract.scala:302)
	at build_db.Extract$.$anonfun$extract$38$adapted(Extract.scala:300)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
	at scala.collection.immutable.List.foldLeft(List.scala:86)
	at build_db.Extract$.extract(Extract.scala:300)
	at build_db.Extract$.$anonfun$main$1(Extract.scala:59)
	at build_db.Extract$.$anonfun$main$1$adapted(Extract.scala:55)
	at scala.Option.map(Option.scala:146)
	at build_db.Extract$.main(Extract.scala:55)
	at cli.Ptolemy$.main(Ptolemy.scala:29)
	at cli.Ptolemy.main(Ptolemy.scala)
```

and with the example files
`java -jar ../ptolemy.jar extract -g genome_list.txt -o testdb`
```(Thu Apr 04 12:12:29 CLST 2019): Found 3 genome entries
(Thu Apr 04 12:12:29 CLST 2019): --Verifying paths
Exception in thread "main" java.lang.AssertionError: assumption failed: Invalid assembly file for S288c: /home/sandro/Programas/ptolemy-1.0/testing_data/./test_data/S288c.chr07.fasta
	at scala.Predef$.assume(Predef.scala:252)
	at build_db.Extract$.$anonfun$verifyCorrectGenomeEntries$1(Extract.scala:347)
	at build_db.Extract$.$anonfun$verifyCorrectGenomeEntries$1$adapted(Extract.scala:346)
	at build_db.Extract$.$anonfun$extract$2(Extract.scala:69)
	at build_db.Extract$.$anonfun$extract$2$adapted(Extract.scala:69)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at build_db.Extract$.extract(Extract.scala:69)
	at build_db.Extract$.$anonfun$main$1(Extract.scala:59)
	at build_db.Extract$.$anonfun$main$1$adapted(Extract.scala:55)
	at scala.Option.map(Option.scala:146)
	at build_db.Extract$.main(Extract.scala:55)
	at cli.Ptolemy$.main(Ptolemy.scala:29)
	at cli.Ptolemy.main(Ptolemy.scala)
```

what can I do?
thank you in advance

**Comment by ba1** [comment]
I got the same error. For the 

Testing data
- You need to create the output directory 'ptolemy_db' before running
- The paths in the genome_list file are incorrectly set to 'test_data'  as directory name instead of 'data'

My issue for the IndexOutOfBoundsException was the differing contig names specified in the fasta vs the gff. The fasta headers have to contain only and match exactly the gff contig ids (first column).
